### ISSUE TITLE
attachments for meeting notes not stored or at least not linked

### ISSUE THREAD

**Issue by breunigs** [bv-hh/bv-hh#270]
For example this meeting note has an attachment:
https://sitzungsdienst-altona.hamburg.de/bi/to020.asp?TOLFDNR=1038941

However, the corresponding page on bv-hh doesn't seem to link it:
https://bv-hh.de/altona/meetings/20-06-2022-sitzung-des-verkehrsausschusses-3079/protokoll#3766927

It would be nice if they could be mirrored as well.

**Comment by tbk303** [comment]
Ah, never came across these, yet ;) There are always new features of Allris to discover...

Will try to integrate this, but that requires some work, probably not too soon...

**Comment by tbk303** [comment]
Fixed with #277 

Probably needs some fine tuning after crawling some more documents "in the wild" :)
