### ISSUE TITLE
show page by allris id

### ISSUE THREAD

**Issue by breunigs** [bv-hh/bv-hh#273]
This is a very specific thing for my use case, namely linking to the sources on veloroute.hamburg. Essentially, I'd like to keep the original Sitzungsdienst because it's the actual source. However, I'd also like to link to bv-hh because it's much nicer to use on mobile, and it doesn't have the weird expiring attachment links. Of course, ideally I can do that without having to find two links for each linked document. I currently only store the URL (e.g. `https://sitzungsdienst-altona.hamburg.de/bi/vo020.asp?VOLFDNR=1013065`) but parsing that into `altona` and and `1013065` is no biggie. Skimming over the code, I see that bv-hh stores an `allris_id`, which is probably this number.

Would you accept a PR that accepts the document/meeting allris id and redirects to the proper URL?

**Comment by tbk303** [comment]
Sure!

**Comment by tbk303** [comment]
Meetings and documents are now accessible via allris id using URLs like these:

https://bv-hh.de/altona/meetings/allris?allris_id=1003042
https://bv-hh.de/altona/documents/allris?allris_id=1013135

**Comment by breunigs** [comment]
any chance to extend this towards the meeting minutes? I didn't even realize that the meetings themselves have an extra ID, my bad!

**Comment by tbk303** [comment]
Hm, I am not sure whether the minutes have an allris id ... at least I only have the allris_ids for single minutes items like these: https://sitzungsdienst-altona.hamburg.de/bi/to020.asp?TOLFDNR=1039216

But bv-hh has no respective single-minutes-item-view, only the full minutes for a meeting.

So do you want a redirect from the allris_id of a single minutes item to the full minutes for that meeting?

**Comment by breunigs** [comment]
Yes, that would be ideal. I would have to double check, but if the anchor is included in the `Location:` header, the browsers should jump the correct section on the all notes page. If they don't, I don't think it's worth it – sending users to the full minutes page can be confusing if only a specific one is expected.

**Comment by tbk303** [comment]
Try this:

https://bv-hh.de/altona/agenda_items/allris?allris_id=1039124

**Comment by breunigs** [comment]
works perfectly!
