### ISSUE TITLE
attachments for Drucksachen are missing

### ISSUE THREAD

**Issue by breunigs** [bv-hh/bv-hh#458]
Hi,

it seems that attachments for regular Drucksachen are not mirrored anymore. For example:
*  1 attachment
    * https://sitzungsdienst-harburg.hamburg.de/bi/vo020.asp?VOLFDNR=1011433
    * https://bv-hh.de/harburg/documents/a-26-ost-aktueller-planungsstand-170013
* multiple attachments
   * https://sitzungsdienst-wandsbek.hamburg.de/bi/vo020.asp?VOLFDNR=1020095
   * https://bv-hh.de/wandsbek/documents/baumassnahme-buendnis-fuer-den-fuss-und-radverkehr-veloroute-6-teilbaumassnahme-abschnitt-w18-berner-heerweg-zwischen-august-krogmann-strasse-und-neusurenland-170670

I am fairly certain this worked a while ago, and has been broken since at least the December 2023.

**Comment by tbk303** [comment]
Thanks for the report, will investigate...

**Comment by tbk303** [comment]
This was just a view issue, attachments are now be displayed correctly.
